name: flutter_app
description: NTUST Life TAT, convenient, concise, fast, powerful, enrich your NTUST life!

# you can use this command to build both android app bundle and ios ipa:
# flutter clean && flutter build ios --split-debug-info=build/app/outputs/symbols --obfuscate && flutter build appbundle --split-debug-info=build/app/outputs/symbols --obfuscate --shrink
# follow the google play new policy in 2021, do not build apk but aab.
# CHECK THE BUILD CODE BEFORE DISTRIBUTION!!
version: 1.5.0+101

environment:
  flutter: ">=3.3.0 <4.0.0"
  sdk: "^3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path: ^1.8.1
  provider: ^6.0.5
  path_provider: ^2.0.14
  quiver: ^3.2.1
  url_launcher: ^6.2.5
  url_launcher_ios: ^6.2.5
  #開啟email phone url...
  logger: ^2.1.0
  #顯示Log
  sprintf: ^7.0.0
  flutter_local_notifications: ^19.4.1
  #通知欄  需修改android原始碼
  rxdart: ^0.27.7
  #通知欄有使用到
  android_intent_plus: ^4.0.3
  device_info_plus: ^9.1.2
  html_unescape: ^2.0.0
  #處理HTML特殊字
  local_auth: ^2.1.6
  #驗證身分指紋
  version: ^3.0.2
  #版本比較
  file_picker: ^6.2.0
  #選擇android資料夾
  #----------store data----------#
  shared_preferences: ^2.0.20
  flutter_cache_manager: ^3.3.0
  #----------internet----------#
  dio: ^5.4.1
  #網路get post API
  dio_cookie_manager: ^3.1.1
  #用於產生cookie_jar與dio接口
  cookie_jar: ^4.0.8
  #可儲存式cookies
  html: ^0.15.2
  #html解析器
  fk_user_agent:
    git:
      url: https://github.com/maeltoukap/fk_user_agent.git
      ref: master
  connectivity_plus: ^5.0.2
  clipboard: ^0.1.3
  #剪貼簿
  #----------WebView----------#
  flutter_inappwebview: ^6.1.0
  #---------icon----------#
  eva_icons_flutter: ^3.1.0
  #https://akveo.github.io/eva-icons/#/
  fluttericon: ^2.0.0
  #https://oblador.github.io/react-native-vector-icons/
  #---------json----------#
  json_annotation: ^4.8.0
  #----------other----------#
  back_button_interceptor: ^7.0.2
  #攔截返回鍵訊息
  #DateTime to String
  package_info_plus: ^8.3.0
  #檢測app版本用於檢查更新
  #----------html viewer----------#
  #flutter_html: ^2.2.1
  flutter_widget_from_html: ^0.14.11
  #----------animation----------#
  flutter_staggered_animations: ^1.1.1
  #listView or gridView動畫
  #----------download----------#
  flutter_downloader: ^1.11.6
  #下載app更新
  open_filex: ^4.3.2
  permission_handler: ^11.3.0
  mime_type: ^1.0.0
  github: ^9.11.0
  #----------Widget----------#
  get: ^4.6.5
  bot_toast: ^4.0.3
  #提供ListView可下拉式更新並且可動態加載
  cached_network_image: ^3.2.3
  #用url顯示圖片
  auto_size_text: ^3.0.0
  #課表顯示有用到
  table_calendar: ^3.0.9
  #顯示行事曆
  expansion_tile_card: ^3.0.0
  fluttertoast: ^8.2.1
  #Toast
  awesome_dialog: ^3.0.2
  #顯示Error時用到
  flutter_slidable: ^3.0.1
  #email使用可左右滑抽屜
  flutter_spinkit: ^5.1.0
  #等待動畫
  card_swiper: ^3.0.1
  #公告
  flutter_markdown: ^0.6.14
  numberpicker: ^2.1.1
  #選擇學期
  alice_lightweight: ^3.1.0
  pretty_json: ^2.0.0
  icalendar_parser: ^2.0.0
  charset_converter: ^2.1.1

  # Firebase
  firebase_core: ^2.8.0
  firebase_analytics: ^10.1.6
  firebase_crashlytics: ^3.0.17
  firebase_remote_config: ^4.3.17
  firebase_messaging: ^14.3.0
  google_mobile_ads: ^4.0.0
  flutter_svg: ^2.0.10+1
  screenshot: ^3.0.0
  photo_view: ^0.14.0
  shimmer: ^3.0.0

dependency_overrides:
  intl: ^0.18.0
  wakelock_plus: 1.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  #flutter pub run flutter_launcher_icons:main -f pubspec.yaml
  #利用以下的flutter_icons設定icon位置
  flutter_native_splash: ^2.2.19
  #flutter pub run flutter_native_splash:create
  #---------json----------#
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/image/
    - assets/launcher/

  fonts:
    - family: MyIcon
      fonts:
        - asset: assets/fonts/MyIcon.ttf
    - family: MyFont
      fonts:
        - asset: assets/fonts/GenSenRounded-R.ttc
        - asset: assets/fonts/GenSenRounded-B.ttc
          weight: 600
        - asset: assets/fonts/GenSenRounded-EL.ttc
          weight: 200

flutter_intl:
  enabled: true

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/ios-icon.png"
  image_path_android: "assets/launcher/android-icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash/splash.png