// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhpUpgxwHDQosgCwZnxhLC0es4WVZcC54',
    appId: '1:935354808798:android:07c9dc9df596c4f6edc54f',
    messagingSenderId: '935354808798',
    projectId: 'ntust-tat',
    storageBucket: 'ntust-tat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpYyc8wkaEUZbZawpBkE7VEH9Wb5zSDRQ',
    appId: '1:935354808798:ios:a33fd0b3c2a8e449edc54f',
    messagingSenderId: '935354808798',
    projectId: 'ntust-tat',
    storageBucket: 'ntust-tat.appspot.com',
    androidClientId: '935354808798-p6r0fn8gutcenvscena9u8tjmhslg5mh.apps.googleusercontent.com',
    iosClientId: '935354808798-1ernito5j3naqm6iga1koc9cp3qkk8mm.apps.googleusercontent.com',
    iosBundleId: 'club.ntust.tat',
  );
}
